name: API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install fastapi uvicorn pytest requests

      - name: Start FastAPI server
        run: |
          uvicorn apiserver:app --host 127.0.0.1 --port 8000 &
        env:
          PYTHONUNBUFFERED: 1

      - name: Wait for server to be ready
        run: sleep 5  # Give time for the server to start

      - name: Run tests
        run: pytest testautomation.py
